@apiHost = http://localhost:3000
@emulatorHost = http://127.0.0.1:9099
@idToken = eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJuYW1lIjoidGVzdCB1c2VyIiwicGljdHVyZSI6IiIsImVtYWlsIjoiYmRia3gyODZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJhdXRoX3RpbWUiOjE3NjQyNDMyODQsInVzZXJfaWQiOiJEa3k0ZXRDVTNBc01vejJxYVFncGZHdXZBOU5hIiwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJiZGJreDI4NkBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9LCJpYXQiOjE3NjQyNDMyODQsImV4cCI6MTc2NDI0Njg4NCwiYXVkIjoiZ3ltLW5vdGUtYXBwIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2d5bS1ub3RlLWFwcCIsInN1YiI6IkRreTRldENVM0FzTW96MnFhUWdwZkd1dkE5TmEifQ.

###

# Firebase Auth Sign In with Email and Password
POST {{emulatorHost}}/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=fake-api-key
content-type: application/json

{
  "email": "bdbkx286@gmail.com",
  "password": "password",
  "returnSecureToken": true
}

###

# GET User Data
GET {{apiHost}}/api/v1/user
Authorization: Bearer {{idToken}}

###

# GET Exercises
GET {{apiHost}}/api/v1/exercises
Authorization: Bearer {{idToken}}

###
